# The closed set. These must stay identical to the keys in
# SymptomAnalysisServiceImpl.SPECIALIZATION_KEYWORDS on the Java side —
# they are used to look up doctors, so an unknown value returns nobody.
SPECIALIZATIONS: tuple[str, ...] = (
    "GENERAL_PHYSICIAN", "CARDIOLOGIST", "DERMATOLOGIST", "NEUROLOGIST",
    "ORTHOPEDIC", "PEDIATRICIAN", "GYNECOLOGIST", "PSYCHIATRIST",
    "OPHTHALMOLOGIST", "ENT_SPECIALIST", "DENTIST", "GASTROENTEROLOGIST",
    "PULMONOLOGIST", "UROLOGIST", "ONCOLOGIST", "ENDOCRINOLOGIST",
    "NEPHROLOGIST",
)

FALLBACK = "GENERAL_PHYSICIAN"

# Attached by the server to every response. Never generated by the model,
# so it cannot be reworded, softened, or omitted.
DISCLAIMER = (
    "This is an automated suggestion to help you choose a specialist. "
    "It is not a medical diagnosis. If symptoms are severe or worsening, "
    "contact emergency services or go to the nearest hospital."
)